AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to deploy FastAPI on ECS

Parameters:
  ECRImageURI:
    Type: String
    Description: URI of the Docker image in ECR
  VpcId:
    Type: String
    Description: VPC ID where ECS will run
  SubnetId:
    Type: String
    Description: Subnet ID for the ECS tasks
  SecurityGroup:
    Type: String
    Description: Security Group for the ECS tasks

Resources:
  FastAPICluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: FastAPICluster

  FastAPITaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: FastAPITask
      NetworkMode: awsvpc
      ContainerDefinitions:
        - Name: fastapi-container
          Image: !Ref ECRImageURI
          Memory: 512
          Cpu: 256
          Essential: true
          PortMappings:
            - ContainerPort: 8000
              HostPort: 8000
              Protocol: tcp

  FastAPIService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref FastAPICluster
      TaskDefinition: !Ref FastAPITaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !Ref SubnetId
          SecurityGroups:
            - !Ref SecurityGroup
          AssignPublicIp: ENABLED

Outputs:
  ServiceUrl:
    Description: "URL of the FastAPI service"
    Value: !Sub "http://${FastAPIService}.loadBalancer.dnsName"
